"""initial schema

Revision ID: e884468cca8e
Revises: 
Create Date: 2026-05-06 16:59:31.663017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.sqltypes  # noqa: F401  — referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'e884468cca8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_problems_difficulty', 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_uid', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_uid'), 'users', ['google_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('metadata', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_user_action', 'activity_logs', ['user_id', 'action'], unique=False)
    op.create_index('idx_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='uq_chat_pair')
    )
    op.create_index('idx_chats_last_message_at', 'chats', ['last_message_at'], unique=False)
    op.create_index('idx_chats_user_1_id', 'chats', ['user_1_id'], unique=False)
    op.create_index('idx_chats_user_2_id', 'chats', ['user_2_id'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('course_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_course_comments_created_at', 'course_comments', ['created_at'], unique=False)
    op.create_index('idx_course_comments_user_id', 'course_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_comments_course_id'), 'course_comments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_comments_id'), 'course_comments', ['id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='free', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('free','paid','trial','comped')", name='ck_enrollments_source'),
    sa.CheckConstraint("status IN ('active','expired','revoked')", name='ck_enrollments_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrollment_per_user_course')
    )
    op.create_index('idx_enrollments_user_course', 'course_enrollments', ['user_id', 'course_id'], unique=False)
    op.create_index('idx_enrollments_user_status', 'course_enrollments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_course_enrollments_id'), 'course_enrollments', ['id'], unique=False)
    op.create_table('course_reactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('reaction_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reaction_type IN ('like', 'dislike')", name='ck_course_reactions_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_index('idx_course_reactions_course_id', 'course_reactions', ['course_id'], unique=False)
    op.create_table('email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_otps_user_active', 'email_otps', ['user_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index('idx_follows_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follows_following_id', 'follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('lesson_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('lesson_id', sa.String(length=128), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_bookmark_per_user_lesson')
    )
    op.create_index('idx_bookmarks_user_course', 'lesson_bookmarks', ['user_id', 'course_id'], unique=False)
    op.create_index('idx_bookmarks_user_created', 'lesson_bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_lesson_bookmarks_id'), 'lesson_bookmarks', ['id'], unique=False)
    op.create_table('lesson_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('lesson_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_note_per_user_lesson')
    )
    op.create_index('idx_notes_user_course', 'lesson_notes', ['user_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_lesson_notes_id'), 'lesson_notes', ['id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('lesson_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False),
    sa.Column('last_position', sa.String(length=64), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('not_started','in_progress','completed')", name='ck_progress_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_per_user_lesson')
    )
    op.create_index('idx_progress_last_accessed', 'lesson_progress', ['user_id', 'last_accessed_at'], unique=False)
    op.create_index('idx_progress_user_course', 'lesson_progress', ['user_id', 'course_id'], unique=False)
    op.create_index('idx_progress_user_status', 'lesson_progress', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('idx_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_object_keys', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('repost_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('code_snippet', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_location', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_posts_problem_id', 'posts', ['problem_id'], unique=False)
    op.create_index('idx_posts_type', 'posts', ['type'], unique=False)
    op.create_index('idx_posts_user_id', 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_deleted_at'), 'posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('problem_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_problem_status', 'problem_submissions', ['problem_id', 'status'], unique=False)
    op.create_index('idx_submissions_user_problem', 'problem_submissions', ['user_id', 'problem_id'], unique=False)
    op.create_index('idx_submissions_user_status', 'problem_submissions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_problem_submissions_id'), 'problem_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_problem_submissions_status'), 'problem_submissions', ['status'], unique=False)
    op.create_table('problem_testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_testcases_id'), 'problem_testcases', ['id'], unique=False)
    op.create_index(op.f('ix_problem_testcases_problem_id'), 'problem_testcases', ['problem_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('meta', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_events_created', 'security_events', ['created_at'], unique=False)
    op.create_index('idx_security_events_event_created', 'security_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_security_events_user_event', 'security_events', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_key', name='uq_user_badge')
    )
    op.create_index('idx_user_achievements_user', 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'target_id', name='uq_user_block_pair')
    )
    op.create_index('idx_user_blocks_blocker', 'user_blocks', ['blocker_id'], unique=False)
    op.create_index('idx_user_blocks_target', 'user_blocks', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_blocks_id'), 'user_blocks', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('interests', sa.String(length=255), nullable=True),
    sa.Column('skills', app.core.sqltypes.JSONBType(), nullable=True),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id'], ['activity_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('idx_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_like')
    )
    op.create_index('idx_post_likes_post_id', 'post_likes', ['post_id'], unique=False)
    op.create_index('idx_post_likes_user_id', 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_table('post_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reporter_id', name='uq_post_report_pair')
    )
    op.create_index('idx_post_reports_created', 'post_reports', ['created_at'], unique=False)
    op.create_index('idx_post_reports_post', 'post_reports', ['post_id'], unique=False)
    op.create_index('idx_post_reports_status', 'post_reports', ['status'], unique=False)
    op.create_index(op.f('ix_post_reports_id'), 'post_reports', ['id'], unique=False)
    op.create_table('comment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'reporter_id', name='uq_comment_report_pair')
    )
    op.create_index('idx_comment_reports_comment', 'comment_reports', ['comment_id'], unique=False)
    op.create_index('idx_comment_reports_created', 'comment_reports', ['created_at'], unique=False)
    op.create_index('idx_comment_reports_status', 'comment_reports', ['status'], unique=False)
    op.create_index(op.f('ix_comment_reports_id'), 'comment_reports', ['id'], unique=False)
    op.create_table('message_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reader_id', name='uq_message_reader')
    )
    op.create_index('idx_message_reads_message_id', 'message_reads', ['message_id'], unique=False)
    op.create_index('idx_message_reads_reader_id', 'message_reads', ['reader_id'], unique=False)
    op.create_index(op.f('ix_message_reads_id'), 'message_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reads_id'), table_name='message_reads')
    op.drop_index('idx_message_reads_reader_id', table_name='message_reads')
    op.drop_index('idx_message_reads_message_id', table_name='message_reads')
    op.drop_table('message_reads')
    op.drop_index(op.f('ix_comment_reports_id'), table_name='comment_reports')
    op.drop_index('idx_comment_reports_status', table_name='comment_reports')
    op.drop_index('idx_comment_reports_created', table_name='comment_reports')
    op.drop_index('idx_comment_reports_comment', table_name='comment_reports')
    op.drop_table('comment_reports')
    op.drop_index(op.f('ix_post_reports_id'), table_name='post_reports')
    op.drop_index('idx_post_reports_status', table_name='post_reports')
    op.drop_index('idx_post_reports_post', table_name='post_reports')
    op.drop_index('idx_post_reports_created', table_name='post_reports')
    op.drop_table('post_reports')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.drop_index('idx_post_likes_user_id', table_name='post_likes')
    op.drop_index('idx_post_likes_post_id', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_messages_session_id', table_name='messages')
    op.drop_index('idx_messages_sender_id', table_name='messages')
    op.drop_index('idx_messages_chat_id', table_name='messages')
    op.drop_index('idx_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_post_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_blocks_id'), table_name='user_blocks')
    op.drop_index('idx_user_blocks_target', table_name='user_blocks')
    op.drop_index('idx_user_blocks_blocker', table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index('idx_user_achievements_user', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index('idx_security_events_user_event', table_name='security_events')
    op.drop_index('idx_security_events_event_created', table_name='security_events')
    op.drop_index('idx_security_events_created', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_problem_testcases_problem_id'), table_name='problem_testcases')
    op.drop_index(op.f('ix_problem_testcases_id'), table_name='problem_testcases')
    op.drop_table('problem_testcases')
    op.drop_index(op.f('ix_problem_submissions_status'), table_name='problem_submissions')
    op.drop_index(op.f('ix_problem_submissions_id'), table_name='problem_submissions')
    op.drop_index('idx_submissions_user_status', table_name='problem_submissions')
    op.drop_index('idx_submissions_user_problem', table_name='problem_submissions')
    op.drop_index('idx_submissions_problem_status', table_name='problem_submissions')
    op.drop_table('problem_submissions')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_deleted_at'), table_name='posts')
    op.drop_index('idx_posts_user_id', table_name='posts')
    op.drop_index('idx_posts_type', table_name='posts')
    op.drop_index('idx_posts_problem_id', table_name='posts')
    op.drop_index('idx_posts_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_index('idx_notifications_user_created', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_index('idx_progress_user_status', table_name='lesson_progress')
    op.drop_index('idx_progress_user_course', table_name='lesson_progress')
    op.drop_index('idx_progress_last_accessed', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_notes_id'), table_name='lesson_notes')
    op.drop_index('idx_notes_user_course', table_name='lesson_notes')
    op.drop_table('lesson_notes')
    op.drop_index(op.f('ix_lesson_bookmarks_id'), table_name='lesson_bookmarks')
    op.drop_index('idx_bookmarks_user_created', table_name='lesson_bookmarks')
    op.drop_index('idx_bookmarks_user_course', table_name='lesson_bookmarks')
    op.drop_table('lesson_bookmarks')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index('idx_follows_following_id', table_name='follows')
    op.drop_index('idx_follows_follower_id', table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_index('idx_email_otps_user_active', table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index('idx_course_reactions_course_id', table_name='course_reactions')
    op.drop_table('course_reactions')
    op.drop_index(op.f('ix_course_enrollments_id'), table_name='course_enrollments')
    op.drop_index('idx_enrollments_user_status', table_name='course_enrollments')
    op.drop_index('idx_enrollments_user_course', table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_course_comments_id'), table_name='course_comments')
    op.drop_index(op.f('ix_course_comments_course_id'), table_name='course_comments')
    op.drop_index('idx_course_comments_user_id', table_name='course_comments')
    op.drop_index('idx_course_comments_created_at', table_name='course_comments')
    op.drop_table('course_comments')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index('idx_chats_user_2_id', table_name='chats')
    op.drop_index('idx_chats_user_1_id', table_name='chats')
    op.drop_index('idx_chats_last_message_at', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index('idx_activity_logs_user_created', table_name='activity_logs')
    op.drop_index('idx_activity_logs_user_action', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index('idx_problems_difficulty', table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
