/**
 * topicsLoader.js
 * Loads the problem catalog for ProblemList / TopicProblems / the IDE.
 *
 * List views render from src/assets/problems-manifest.json — a small index
 * generated by scripts/generate-problems-manifest.mjs (runs on predev /
 * prebuild). Full problem JSONs are loaded individually, only when a
 * problem is actually opened (loadProblemRaw). Previously loadAllTopics()
 * imported every problem file up front: ~750 requests / >3 MB to show a list.
 *
 * Expected topic shape:
 *   { id, name, icon, problems: [{ id, title, difficulty, category, ... }] }
 */

// Lazy per-file loaders, used only for single-problem loads on demand.
const modules = import.meta.glob([
    '../assets/**/*.json',
    '!../assets/problems-manifest.json',
]);

// Map folder names (lowercase kebab-case) to display names + emoji icons.
// Folder naming convention: all lowercase, words separated by hyphens.
// Viz folder names mirror asset folder names exactly under public/visualizations/.
const TOPIC_META = {
  'arrays':                 { name: 'Arrays',                 icon: '📊' },
  'binary-trees':           { name: 'Binary Trees',           icon: '🌳' },
  'dynamic-programming':    { name: 'Dynamic Programming',    icon: '⚡' },
  'graph':                  { name: 'Graph',                  icon: '🕸️' },
  'linked-list':            { name: 'Linked List',            icon: '🔗' },
  'maths':                  { name: 'Maths',                  icon: '➗' },
  'recursion':              { name: 'Recursion',              icon: '🔄' },
  'searching-and-sorting':  { name: 'Searching & Sorting',    icon: '🔍' },
  'stack-queue-and-heap':   { name: 'Stacks, Queues & Heaps', icon: '📚' },
  'string':                 { name: 'String',                 icon: '🔤' },
  'trie':                   { name: 'Trie',                   icon: '🌿' },
};

let cachedTopics = null;

/**
 * Loads all topics from the manifest (one small request, cached after the
 * first call). Problem entries carry list metadata plus _vizFile/_topicKey;
 * use loadProblemRaw() to get a problem's full JSON.
 */
export async function loadAllTopics() {
  if (cachedTopics) return cachedTopics;

  const { default: manifest } = await import('../assets/problems-manifest.json');

  const topicsMap = {};
  for (const entry of manifest) {
    const topicKey = entry.topicKey;
    if (!topicsMap[topicKey]) {
      const meta = TOPIC_META[topicKey] || {
        name: topicKey.charAt(0).toUpperCase() + topicKey.slice(1),
        icon: '📁',
      };
      topicsMap[topicKey] = {
        id: topicKey,
        name: meta.name,
        icon: meta.icon,
        problems: [],
      };
    }

    topicsMap[topicKey].problems.push({
      id:         entry.id,
      title:      entry.title,
      difficulty: entry.difficulty,
      category:   entry.category,
      tags:       entry.tags,
      likes:      entry.likes,
      // Visualization helpers — used by ProblemPanel to build the iframe src
      _vizFile:   entry.vizFile,
      _topicKey:  entry.topicKey,
    });
  }

  // Sort topics alphabetically; problems keep manifest (filename) order
  cachedTopics = Object.values(topicsMap).sort((a, b) =>
    a.name.localeCompare(b.name)
  );

  return cachedTopics;
}

/**
 * Loads one problem's full JSON on demand (statement, examples, solutions…).
 * Returns null if the file doesn't exist — e.g. a stale manifest entry.
 */
export async function loadProblemRaw(topicKey, vizFile) {
  const loader = modules[`../assets/${topicKey}/${vizFile}.json`];
  if (!loader) return null;
  const mod = await loader();
  return mod.default ?? mod;
}
